version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: sentinelx-mosquitto
    ports:
      - "5555:1883"
      - "8883:8883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./infra/certs:/mosquitto/certs
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: sentinelx-backend
    ports:
      - "3000:3000"
    depends_on:
      - mosquitto
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: sentinelx-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped
